### ISSUE TITLE
关于KITTI测试结果

### ISSUE THREAD

**Issue by moyans** [manutdzou/KITTI_SSD#10]
@handong1587 @manutdzou 你好，请问能公布下在KITTI测试集上取得的结果么？

**Comment by manutdzou** [comment]
测试集结果需要在线提交，我并未去注册参加刷榜




发自网易邮箱大师
在2017年08月25日 14:24，Moyan 写道：

@handong1587@manutdzou 你好，请问能公布下在KITTI测试集上取得的结果么？

**Comment by moyans** [comment]
Whatever ， Thanks
